### ISSUE TITLE
Adding TCP BBR 

### ISSUE THREAD

**Issue by LiveChief** [flxn/tor-relay-configurator#15]
`https://github.com/LiveChief/tcp-bbr-install`

`https://medium.com/google-cloud/tcp-bbr-magic-dust-for-network-performance-57a5f1ccf437
`

`https://cloud.google.com/blog/products/gcp/tcp-bbr-congestion-control-comes-to-gcp-your-internet-just-got-faster
`

this make TCP super fast and should help speed up tor.

**Comment by flxn** [comment]
Interesting. 
I can't find any resources wether Tor will benefit from this or not.
I'll look into that, maybe it could be useful.

**Comment by LiveChief** [comment]
`https://trac.torproject.org/projects/tor/ticket/30420`

**Comment by irl** [comment]
I really believe this is a bad idea, and will harm the Tor network. BBR is designed for the use case of YouTube, where a user watches one video at a time. Tor relays maintain thousands of TCP connections to other relays, and those flows won't compete fairly when BBR is used.

In the best case, the bandwidth scanner will just notice that mostly your relay offers poor performance. In the worst case, the bandwidth scanner gets lucky and is using the BBR flow that wins, and then all the users get terrible performance from your relay until it's remeasured.

**Comment by LiveChief** [comment]
`https://metrics.torproject.org/rs.html#details/3BBE9AF4240D169FBA206DCC95D7FDE20C5226C6`'

Testing it out on this RELAY

Will host it for 90 days.

**Comment by flxn** [comment]
After some reading I came to a similar conclusion as @irl 
BBR behaves unfair towards other - non BBR - connections. Since a Tor node is connected to hundreds of other nodes, most of which will likely not use BBR, it will restrict the traffic flow, defeating the purpose of a distributed network.
See this presentation: https://ripe76.ripe.net/presentations/10-2018-05-15-bbr.pdf

<img width="674" alt="image" src="https://user-images.githubusercontent.com/6113032/57435680-46a0e880-723e-11e9-8019-1e7e64f3663c.png">

**Comment by irl** [comment]
@LiveChief Even if your relay shows improvements in bandwidth, it's only helping *your* relay, not the network. This is not a good scientific experiment.

**Comment by LiveChief** [comment]
@irl what if we forced bbr with every tor node?

**Comment by irl** [comment]
@LiveChief my understanding from speaking to Internet engineering researchers is it would pretty quickly kill the Tor network. You should look at tools like Shadow if you wanted to run simulations to try it out.

**Comment by LiveChief** [comment]
> @LiveChief my understanding from speaking to Internet engineering researchers is it would pretty quickly kill the Tor network. You should look at tools like Shadow if you wanted to run simulations to try it out.

whats Shadow???

Url please

**Comment by irl** [comment]
@LiveChief http://shadow.github.io/

**Comment by LiveChief** [comment]
Thank you good sir.
