### ISSUE TITLE
Remove dependencies to Cloudfare, Google and Twitter

### ISSUE THREAD

**Issue by sistein** [flxn/tor-relay-configurator#18]
Hi, 

it would be great if Fonts and JS would be used more privacy friendly - locally hosted for example or one of the other solutions available ;-). 

For Twitter it would be nice if a solution like shariff by heiseonline would be used (https://github.com/heiseonline/shariff ). 

Thx :-)

**Comment by flxn** [comment]
Good idea, I'll whip something up over the weekend.

**Comment by flxn** [comment]
All third-party dependencies have been removed. The only thing left are my self-hosted analytics.
