### ISSUE TITLE
Backup -> Restore

### ISSUE THREAD

**Issue by kanet0x** [flxn/tor-relay-configurator#19]
How can I restore my tor-relay?
I have the fingerprint and the secret_id_key

**Thanks for your help!**

**Comment by flxn** [comment]
If you backed up the keys of your node (by default stored in /var/lib/tor/keys) you can stop Tor, overwrite those files with your backup and start Tor again and it should just work.  
Make sure that the keys directory has the right permissions. You can run `chown debian-tor /var/lib/tor/keys` after copying to make sure the Tor user owns the directory.
Look at the log file for any errors that may occur, most of the time they are quite helpful.

**Comment by kanet0x** [comment]
Yeah I forgot the permissions. Now it works. Thanks.
