### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by ridgewell** [flxn/tor-relay-configurator#22]
What work would need to be done in order to update Tor-relay-configurator to Ubuntu 20.04? 

Guessing it's more than just updating apt links, and is dependent on when the Tor Project starts providing a apt repo for Ubuntu 20.04: https://2019.www.torproject.org/docs/debian.html.en

**Comment by flxn** [comment]
Thanks for the reminder!
It is not listed yet on the page but in the repository there exsists a package for 20.04 so i added it to the dropdown and also removed some old distributions.
