### ISSUE TITLE
Unable to Generate Config 

### ISSUE THREAD

**Issue by foxy6520** [flxn/tor-relay-configurator#32]
Error: file_put_contents(): Only -1 of 8022 bytes written, possibly out of free disk space

How to reproduce issue 
------------------------------
**1. Enter the information to the fields 
2. Click generate 
3. Error :)**

**Comment by flxn** [comment]
Thanks for noticing!
Should be fixed now.

**Comment by foxy6520** [comment]
> Thanks for noticing! Should be fixed now.

I was just now writing an email. 

let me check it out 👍

**Comment by foxy6520** [comment]
It works 👍  

Thanks for your help 

@flxn
