### ISSUE TITLE
Site storage error

### ISSUE THREAD

**Issue by Joshuah143** [flxn/tor-relay-configurator#35]
When I go through the steps to create a script I get this error:

> Error: file_put_contents(): Only -1 of 8054 bytes written, possibly out of free disk space

Any ideas?
<img width="1440" alt="Screen Shot 2022-02-19 at 5 24 25 PM" src="https://user-images.githubusercontent.com/83801098/154823657-b88f3b28-47aa-44b5-a6d5-2663e595a927.png">

**Comment by lidarbtc** [comment]
I have a same issue.

**Comment by flxn** [comment]
Sry, I'm having some disk usage issues caused by another application running on the same serve. 
The configurator should work again.

**Comment by lidarbtc** [comment]
thank you!
