### ISSUE TITLE
Add options for IPv6

### ISSUE THREAD

**Issue by imcdona** [flxn/tor-relay-configurator#6]
Would be nice if there were options to enable IPv6 on exit nodes.

A checkbox for IPv6 could be added that when selected would add` IPv6Exit 1` along with the associated `ExitPolicy accept6 `and `ExitPolicy reject6 ` entries.

**Comment by flxn** [comment]
IPv6 support has been added but i need to do some more testing before it will be live.

**Comment by sistein** [comment]
Thanks for the fast implementation. I just tested it and came across the problem that "scope global" is called "scope link" in my setting.

**Comment by flxn** [comment]
AFAIK the link local address is not routable, only the global one is. Can you ping your servers IPv6 link address from outside it's local network?
My server for example has two IPv6 address blocks, one for LAN and one global that's accessible from the internet.
